### ISSUE TITLE
RPM is missing package

### ISSUE THREAD

**Issue by simi823** [ndmanvar/Python-Behave-Selenium#8]
Using Bamboo to create a build plan for testing parallel, but it errors because parse module is missing:
11-Apr-2016 08:45:09    Traceback (most recent call last):
11-Apr-2016 08:45:09      File "behave-parallel/bin/behave", line 42, in <module>
11-Apr-2016 08:45:09        sys.exit(behave_main0())
11-Apr-2016 08:45:09      File "behave-parallel/bin/behave", line 31, in behave_main0
11-Apr-2016 08:45:09        from behave.**main** import main as behave_main
11-Apr-2016 08:45:09      File "/opt/bamboo/bamboo-agent-home/xml-data/build-dir/QA-WEAT-JOB1/behave-parallel/behave/**init**.py", line 22, in <module>
11-Apr-2016 08:45:09        from behave.matchers import step_matcher
11-Apr-2016 08:45:09      File "/opt/bamboo/bamboo-agent-home/xml-data/build-dir/QA-WEAT-JOB1/behave-parallel/behave/matchers.py", line 4, in <module>
11-Apr-2016 08:45:09        import parse
11-Apr-2016 08:45:09    ImportError: No module named parse

**Comment by simi823** [comment]
Figured it out
